# Site settings
title: 'Parikshit Bajpai'
description: 'Personal Page'
url: 'https://parikshitbajpai.github.io'
baseurl: ''
profilepic: '/images/my_image.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
# font_awesome: '/fonts/fontawesome.js'

author:
  name: 'Parikshit Bajpai'
  email: 'parikshit.bajpai@ontariotechu.net'
  twitter_username: 'pbajpai07'
  facebook_username: 'parikshit.bajpai'
  github_username:  'parikshitbajpai'
  linkedin_username:  'parikshit-bajpai'
  instagram_username: 'bajpaiparikshit'
  lab_website: 'nuclear.ontariotechu.ca/piro'
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# plugins: ['jekyll-paginate']
# exclude: ['README.md', 'screenshot-overview.png']
